### PR TITLE
Style spacing tweaks - reduce margin on level-2 list items

### PR DESCRIPTION
**Pull request by jbarnicle**

### CODE REVIEW

**Comment by cmc333333** [comment]
Doesn't this conflict with https://github.com/18F/regulations-site/pull/100 ?

**Comment by jbarnicle** [comment]
We don't want any margin in the atf-site - this setting overrides what is in -site.  I can't say for sure we don't want the 1em margin in the base theme.  With different font settings it might not be the case.

**Comment by cmc333333** [comment]
@xtine can you verify this and #100? I know you were playing with that originally.

**Comment by jbarnicle** [comment]
Might want to loop @jehlers in on this - this was a spacing tweak she requested.

**Comment by jbarnicle** [comment]
I should also point out that there was no net change on list spacing in https://github.com/18F/regulations-site/pull/100 The style was duplicated in typography.less and paragraph-markers.less. The effective css rule was the one paragraph-markers.less because it appeared later.  I moved it and the effective value to typography.less as that was were the rest of the general list rules were being set.

**Comment by xtine** [comment]
This actually doesn't affect the paragraph markers since there is already a rule that overrides the very first list item paragraph margins. LGTM.

**Pull request merged**
