### PR TITLE
Update ATF Logo

### PR DESCRIPTION
**Pull request by jbarnicle**

### CODE REVIEW

**Comment by cmc333333** [comment]
@jbarnicle there's also https://github.com/18F/atf-eregs/blob/master/atf_eregs/templates/regulations/logo-large.html

Would it make sense just to merge the images?

**Comment by cmc333333** [comment]
@jbarnicle [says](https://github.com/18F/atf-eregs/commit/dad15e041eb2dbd8108c231f6eecec76b8d6577f)
> I actually think we should have a new image for the 404 page - it's very blurry at that resolution.
>
> https://atf-eregs.18f.gov/448
> 
> Is that what you were asking?
> 
> @jehlers What do you think.

**Comment by cmc333333** [comment]
@jbarnicle Sure - let's make a ticket for the 404 page. Would it make sense to merge the logo and text images into a single "logo" image, though? We're expecting "logo" to be an extension point -- it'd be nice if we assumed it was a single image.

**Comment by jbarnicle** [comment]
I really don't have a strong opinion either way on this.  My own take on this was to really limit theming to the area between the header / and footer, but I think I was alone in that line of thought in talking to Theresa and Jen.   But if Jen wants to combine the two images into one - that's fine by me - I don't have the photoshop skills to do that myself.

**Pull request merged**
