### PR TITLE
fixing notice alignment

### PR DESCRIPTION
**Pull request by donjo**
closes 18f/atf-eregs#321

### CODE REVIEW

**Comment by cmc333333** [comment]
@donjo - this seems like the wrong solution, it's replacing one arbitrary width with another. Consider what happens when we get non-3-digit regulation numbers. I think the correct approach would be to move the alert into the `reg-sub-title` div above.

**Comment by donjo** [comment]
Good point. So moving it into the div creates something like this by default which makes sense to me. 

screen shot 2016-02-03 at 12 48 01 pm

and cleans up the section hover effect a bit

screen shot 2016-02-03 at 12 49 41 pm

the one question would be do we think people would still understand the view new amendment portion to be a separate clickable area from the area that surrounds it. To me it does as it has its own independent hover effect but what does @jehlers think

**Comment by jehlers** [comment]
I think that makes a lot of sense @donjo! Maybe match the space above the title to separate the title from the stroke that starts the new amendment - just to give the title some space to breathe?

**Comment by donjo** [comment]
@jehlers something like this? 

screen shot 2016-02-04 at 9 54 02 am

that just kinda hangs out in the open. there's also this style which is closer to the original without being full width as a result of it being inside the title container:

screen shot 2016-02-04 at 9 58 22 am

**Comment by jehlers** [comment]
@donjo I like the first one! The second one is probably closer to the original design, but I like the new amendment notice getting closer to the title text to show their relationship better. Does that make sense?

**Comment by donjo** [comment]
closing because this is actually going to be a regulations-site PR

**Pull request closed without merging**
